language: csharp
solution: lizzie.sln
mono: none
dotnet: 2.0.0
script:
 - dotnet restore
 - dotnet build ./lizzie.sln --configuration Release
 - dotnet test ./lizzie.tests/lizzie.tests.csproj --configuration Release