language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
script:
  - xbuild /p:Configuration=Release lizzie.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.8.0/tools/nunit3-console.exe ./lizzie.Tests/bin/Release/lizzie.tests.dll